### ISSUE TITLE
Plugin Error EventBus3 Intellij Plugin threw an uncaught PluginException.

### ISSUE THREAD

**Issue by yangxijun** [likfe/eventbus3-intellij-plugin#1]
大哥, 刚刚收到你的邮件, 我这边运行报错啊

**Comment by likfe** [comment]
请回复我邮件让我知道你的联系方式

**Comment by likfe** [comment]
错误详情： `Unsupported major.minor version 52.0` 

由于编译本插件时，使用的是最新的 `Intellij Plugin SDK` ，建议：
- 使用 `JAVA8`
- `buildToolsVersion` >= 24.0.1

**Comment by MIkeeJY** [comment]
buildtools 用23.0.3没效果么？我用的studio2.2的版本

**Comment by likfe** [comment]
你可以尝试下，理论上和 `buildtools` 版本关系不大，studio 2.2 上我测试的是正常工作的。
