### ISSUE TITLE
post方法和Subscribe方法的对象是继承关系后无法正常跳转

### ISSUE THREAD

**Issue by LitterSun** [likfe/eventbus3-intellij-plugin#10]
`EventBus.getDefault().post(new SonMessage());`

```
@Subscribe
public void onMessage(Message message) {

}
```
这里SonMessage是Message子类，这时候就无法正常跳转了

**Comment by LitterSun** [comment]
麻烦看一下能不能解决问题 #11

**Comment by likfe** [comment]
拉取 `dev` 分支后修改再发 merge 到 dev 分支的请求吧。 dev 稍微进行了重构，更方便理解和扩展。

**Comment by LitterSun** [comment]
> 拉取 `dev` 分支后修改再发 merge 到 dev 分支的请求吧。 dev 稍微进行了重构，更方便理解和扩展。

已经添加到dev分支 #12
