### ISSUE TITLE
EventBus.post 没有显示导航

### ISSUE THREAD

**Issue by liaolintao** [likfe/eventbus3-intellij-plugin#20]
EventBus3-IDEA
2020.0.1

Android Studio 4.1

如图所示, 只有`EventBus.getDefault().post`才显示导航图标, 最早的版本, 是都会显示的;
希望, 不要只匹配`EventBus.getDefault()`开头, 而是匹配EventBus这个类的.post方法;
[origin PsiUtils](https://github.com/kgmyshin/eventbus3-intellij-plugin/blob/master/src/com/kgmyshin/ideaplugin/eventbus3/PsiUtils.java)
```
        EventBus eventBus = getEventBus();
        eventBus.post(new Object());
        EventBus defaultEventBus = EventBus.getDefault();
        defaultEventBus.post(new Object());
        EventBus.getDefault().post(new Object());
```

![image](https://user-images.githubusercontent.com/14138300/96204435-e8ca1180-0f96-11eb-9fee-8aae7c9c87a9.png)

**Comment by likfe** [comment]
fixed [v2020.0.2](https://github.com/likfe/eventbus3-intellij-plugin/releases/tag/v2020.0.2)
